apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-svc"
  namespace: "{{ .Values.namespace }}"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: "{{ .Chart.Name }}"
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}         # Exposed service port
      targetPort: {{ .Values.service.targetPort }} # Pod's internal port
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
