replicaCount: 1

image:
  repository: 192.168.10.222:5001/zora-fe
  tag: BUILD_TAG_PLACEHOLDER
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30081

namespace: default

resources: {}
  
